name: Deploy Build To Firebase

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:  
  build:
    name: Build
    runs-on: macos-12
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Firebase-Tools
      run: |
        yarn add firebase-tools
        echo "$(yarn global bin)" >> $GITHUB_PATH
            
    - name: Bundle install
      run: bundle install

    - name: Build and Test
      run: bundle exec fastlane buildAndTest

    - name: Match Ad-hoc
      run: bundle exec fastlane syncAdHocStagingCodeSigning
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

    - name: Build App and Distribute to Firebase
      run: bundle exec fastlane buildStagingAndUploadToFirebase --verbose
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
